import Collatz.Cycle
import Collatz.Radius4

namespace Collatz
namespace OddCycle

variable {L : ℕ} [NeZero L]

/-- Length of the ordinary unaccelerated orbit segment represented by one full
traversal of an odd cycle. This remains useful for the bridge back to `step`,
but it is not the denominator-compatible Radius-4 word length. -/
def ordinaryPeriod (c : OddCycle L) : ℕ := c.totalExponent + L

/-- The ordinary traversal length is nonzero. -/
theorem ordinaryPeriod_pos (c : OddCycle L) : 0 < c.ordinaryPeriod := by
  have hL : 0 < L := Nat.pos_of_ne_zero (NeZero.ne L)
  simp only [ordinaryPeriod]
  omega

/-- The base odd node is periodic for the ordinary map after `A + L` steps. -/
theorem ordinaryPeriod_periodic (c : OddCycle L) :
    (step^[c.ordinaryPeriod]) (c.node 0) = c.node 0 := by
  simpa [ordinaryPeriod] using c.node_zero_periodic

/-- The cyclic length compatible with the characteristic denominator is `A`,
the total exponent. It is the period of the one-division map `halfStep`. -/
def encodingPeriod (c : OddCycle L) : ℕ := c.totalExponent

/-- The denominator-compatible encoding period is nonzero as a theorem of the
cycle data, not as an additional eligibility hypothesis. -/
theorem encodingPeriod_pos (c : OddCycle L) : 0 < c.encodingPeriod := by
  simpa [encodingPeriod] using c.totalExponent_pos

/-- The base odd node is periodic for `halfStep` after exactly the derived
encoding traversal length `A` (not necessarily its minimal period). -/
theorem encodingPeriod_periodic (c : OddCycle L) :
    (halfStep^[c.encodingPeriod]) (c.node 0) = c.node 0 := by
  simpa [encodingPeriod] using c.node_zero_halfStep_periodic

/-- The cumulative `halfStep` position at which odd node `j` begins. -/
def oddStartPosition (c : OddCycle L) (j : Fin L) : ℕ :=
  c.prefixExponent j.1

/-- Every recorded start position is an actual odd state of the
`halfStep` trajectory generated by the base node. -/
theorem oddStartPosition_is_odd (c : OddCycle L) (j : Fin L) :
    Odd ((halfStep^[c.oddStartPosition j]) (c.node 0)) := by
  rw [oddStartPosition, c.halfStep_reaches_prefix_node j.1]
  exact c.node_odd (j.1 : ZMod L)

/-- Candidate denominator-compatible binary encoding for the Radius-4 layer.

The ambient cyclic length is `A`, not `A + L`. A bit is true exactly at a
cumulative odd-to-odd exponent boundary. This is the natural location of the
`L` odd states in the `halfStep` orbit and is the representation compatible
with `D = 2^A - 3^L`.

The repository deliberately retains the name `oddStartWord` until the converse
parity bridge is formalised: every unmarked position of the `halfStep` orbit
must still be proved even. -/
noncomputable def oddStartWord (c : OddCycle L) : CyclicWord c.encodingPeriod := by
  classical
  exact fun t => decide (∃ j : Fin L,
    t = (c.oddStartPosition j : ZMod c.encodingPeriod))

/-- Membership in the derived word is exactly membership in the finite set of
cumulative odd-start positions. -/
theorem oddStartWord_eq_true_iff (c : OddCycle L) (t : ZMod c.encodingPeriod) :
    c.oddStartWord t = true ↔
      ∃ j : Fin L, t = (c.oddStartPosition j : ZMod c.encodingPeriod) := by
  classical
  simp [oddStartWord]

/-- Every cumulative odd-node start is marked by the derived binary word. -/
theorem oddStartWord_at_start (c : OddCycle L) (j : Fin L) :
    c.oddStartWord (c.oddStartPosition j : ZMod c.encodingPeriod) = true := by
  rw [c.oddStartWord_eq_true_iff]
  exact ⟨j, rfl⟩

/-- Exact Radius 4 for the denominator-compatible derived word. Period
nonzeroness is derived from the cycle data. -/
def IsOddStartRadiusFour (c : OddCycle L) (shift : ZMod c.encodingPeriod) : Prop := by
  letI : NeZero c.encodingPeriod := ⟨Nat.ne_of_gt c.encodingPeriod_pos⟩
  exact IsRadiusFour c.oddStartWord shift

/-- Existence of a nonzero exact Radius-4 rotation of the denominator-compatible
word. -/
def HasOddStartRadiusFourRotation (c : OddCycle L) : Prop := by
  letI : NeZero c.encodingPeriod := ⟨Nat.ne_of_gt c.encodingPeriod_pos⟩
  exact HasRadiusFourRotation c.oddStartWord

end OddCycle
end Collatz
