import Collatz.Cycle
import Collatz.Radius4

namespace Collatz
namespace OddCycle

variable {L : ℕ} [NeZero L]

/-- Length of the ordinary unaccelerated orbit segment represented by one full
traversal of an odd cycle. There are `L` odd steps and `totalExponent` halving
steps. -/
def ordinaryPeriod (c : OddCycle L) : ℕ := c.totalExponent + L

/-- The derived ordinary period is nonzero. -/
theorem ordinaryPeriod_pos (c : OddCycle L) : 0 < c.ordinaryPeriod := by
  have hL : 0 < L := Nat.pos_of_ne_zero (NeZero.ne L)
  simp only [ordinaryPeriod]
  omega

/-- The base odd node is periodic for exactly the derived traversal length
`A + L` (not necessarily its minimal period). -/
theorem ordinaryPeriod_periodic (c : OddCycle L) :
    (step^[c.ordinaryPeriod]) (c.node 0) = c.node 0 := by
  simpa [ordinaryPeriod] using c.node_zero_periodic

/-- The cumulative ordinary-step position at which odd node `j` begins. -/
def oddStartPosition (c : OddCycle L) (j : Fin L) : ℕ :=
  c.prefixStepCount j.1

/-- Every recorded odd-start position is an actual odd state of the ordinary
Collatz trajectory generated by the base node. -/
theorem oddStartPosition_is_odd (c : OddCycle L) (j : Fin L) :
    Odd ((step^[c.oddStartPosition j]) (c.node 0)) := by
  rw [oddStartPosition, c.reaches_prefix_node j.1]
  exact c.node_odd (j.1 : ZMod L)

/-- Candidate binary encoding for the Radius-4 layer.

Its ambient cyclic length is the full ordinary period `A + L`. A bit is true
exactly at a cumulative odd-to-odd block boundary. This definition is derived
from the formal exponent data; it does not assume a Radius-4 theorem.

The repository intentionally calls this an `oddStartWord`, rather than a
parity word, until the converse bridge is proved: every unmarked ordinary
position must be shown to be even. -/
noncomputable def oddStartWord (c : OddCycle L) : CyclicWord c.ordinaryPeriod := by
  classical
  exact fun t => decide (∃ j : Fin L,
    t = (c.oddStartPosition j : ZMod c.ordinaryPeriod))

/-- Membership in the derived word is exactly membership in the finite set of
odd-start positions. -/
theorem oddStartWord_eq_true_iff (c : OddCycle L) (t : ZMod c.ordinaryPeriod) :
    c.oddStartWord t = true ↔
      ∃ j : Fin L, t = (c.oddStartPosition j : ZMod c.ordinaryPeriod) := by
  classical
  simp [oddStartWord]

/-- Every cumulative odd-node start is marked by the derived binary word. -/
theorem oddStartWord_at_start (c : OddCycle L) (j : Fin L) :
    c.oddStartWord (c.oddStartPosition j : ZMod c.ordinaryPeriod) = true := by
  rw [c.oddStartWord_eq_true_iff]
  exact ⟨j, rfl⟩

/-- Exact Radius 4 for the derived odd-start word. The local `NeZero` instance
is justified by `ordinaryPeriod_pos`; nonzeroness is not an extra hypothesis. -/
def IsOddStartRadiusFour (c : OddCycle L) (shift : ZMod c.ordinaryPeriod) : Prop := by
  letI : NeZero c.ordinaryPeriod := ⟨Nat.ne_of_gt c.ordinaryPeriod_pos⟩
  exact IsRadiusFour c.oddStartWord shift

/-- Existence of a nonzero exact Radius-4 rotation of the derived odd-start
word. Again, period nonzeroness is derived from the cycle data. -/
def HasOddStartRadiusFourRotation (c : OddCycle L) : Prop := by
  letI : NeZero c.ordinaryPeriod := ⟨Nat.ne_of_gt c.ordinaryPeriod_pos⟩
  exact HasRadiusFourRotation c.oddStartWord

end OddCycle
end Collatz
