import Collatz.Cycle
import Collatz.Radius4

namespace Collatz
namespace OddCycle

variable {L : ℕ} [NeZero L]

/-- Length of the ordinary unaccelerated orbit segment represented by one full
traversal of an odd cycle. This remains useful for the bridge back to `step`,
but it is not the denominator-compatible Radius-4 word length. -/
def ordinaryPeriod (c : OddCycle L) : ℕ := c.totalExponent + L

/-- The ordinary traversal length is nonzero. -/
theorem ordinaryPeriod_pos (c : OddCycle L) : 0 < c.ordinaryPeriod := by
  have hL : 0 < L := Nat.pos_of_ne_zero (NeZero.ne L)
  simp only [ordinaryPeriod]
  omega

/-- The base odd node is periodic for the ordinary map after `A + L` steps. -/
theorem ordinaryPeriod_periodic (c : OddCycle L) :
    (step^[c.ordinaryPeriod]) (c.node 0) = c.node 0 := by
  simpa [ordinaryPeriod] using c.node_zero_periodic

/-- The cyclic length compatible with the characteristic denominator is `A`,
the total exponent. It is the period of the one-division map `halfStep`. -/
def encodingPeriod (c : OddCycle L) : ℕ := c.totalExponent

/-- The denominator-compatible encoding period is nonzero as a theorem of the
cycle data, not as an additional eligibility hypothesis. -/
theorem encodingPeriod_pos (c : OddCycle L) : 0 < c.encodingPeriod := by
  simpa [encodingPeriod] using c.totalExponent_pos

/-- Typeclass form of the proved nonzeroness of the encoding period. -/
instance encodingPeriod_neZero (c : OddCycle L) : NeZero c.encodingPeriod :=
  ⟨Nat.ne_of_gt c.encodingPeriod_pos⟩

/-- The base odd node is periodic for `halfStep` after exactly the derived
encoding traversal length `A` (not necessarily its minimal period). -/
theorem encodingPeriod_periodic (c : OddCycle L) :
    (halfStep^[c.encodingPeriod]) (c.node 0) = c.node 0 := by
  simpa [encodingPeriod] using c.node_zero_halfStep_periodic

/-- The genuine denominator-compatible parity word of the formal cycle.

At cyclic position `t : ZMod A`, the bit is true exactly when the actual
`halfStep` state reached after the canonical representative `t.val` is odd.
Thus this word is connected to a concrete Collatz-derived orbit by definition;
no generic `CyclicWord` is being relabelled as a cycle encoding. -/
def parityWord (c : OddCycle L) : CyclicWord c.encodingPeriod :=
  fun t => decide (Odd ((halfStep^[t.val]) (c.node 0)))

/-- Expands a parity-word bit back to the corresponding oddness statement on
the actual `halfStep` orbit. -/
theorem parityWord_eq_true_iff (c : OddCycle L) (t : ZMod c.encodingPeriod) :
    c.parityWord t = true ↔
      Odd ((halfStep^[t.val]) (c.node 0)) := by
  simp [parityWord]

/-- The chosen base position of the derived parity word is odd. -/
@[simp]
theorem parityWord_zero (c : OddCycle L) : c.parityWord 0 = true := by
  rw [c.parityWord_eq_true_iff]
  simpa using c.node_odd 0

/-- Exact Radius 4 for the genuine parity word extracted from the formal
`halfStep` orbit. -/
def IsCycleRadiusFour (c : OddCycle L) (shift : ZMod c.encodingPeriod) : Prop :=
  IsRadiusFour c.parityWord shift

/-- The formal cycle has a nonzero exact Radius-4 rotation of its genuine
parity word. -/
def HasCycleRadiusFourRotation (c : OddCycle L) : Prop :=
  HasRadiusFourRotation c.parityWord

/-- The cumulative `halfStep` position at which odd node `j` begins. -/
def oddStartPosition (c : OddCycle L) (j : Fin L) : ℕ :=
  c.prefixExponent j.1

/-- Every recorded start position is an actual odd state of the
`halfStep` trajectory generated by the base node. -/
theorem oddStartPosition_is_odd (c : OddCycle L) (j : Fin L) :
    Odd ((halfStep^[c.oddStartPosition j]) (c.node 0)) := by
  rw [oddStartPosition, c.halfStep_reaches_prefix_node j.1]
  exact c.node_odd (j.1 : ZMod L)

/-- Arithmetic marker word obtained only from cumulative exponent boundaries.

This word is retained as a bridge target because its true positions are easy
to read from the exponent data. It is not used as the definition of the
Collatz parity word: a separate theorem must prove `oddStartWord = parityWord`
before arithmetic facts about these markers may be transferred silently to
Radius-4 statements. -/
noncomputable def oddStartWord (c : OddCycle L) : CyclicWord c.encodingPeriod := by
  classical
  exact fun t => decide (∃ j : Fin L,
    t = (c.oddStartPosition j : ZMod c.encodingPeriod))

/-- Membership in the arithmetic marker word is exactly membership in the
finite set of cumulative odd-start positions. -/
theorem oddStartWord_eq_true_iff (c : OddCycle L) (t : ZMod c.encodingPeriod) :
    c.oddStartWord t = true ↔
      ∃ j : Fin L, t = (c.oddStartPosition j : ZMod c.encodingPeriod) := by
  classical
  simp [oddStartWord]

/-- Every cumulative odd-node start is marked by the arithmetic marker word. -/
theorem oddStartWord_at_start (c : OddCycle L) (j : Fin L) :
    c.oddStartWord (c.oddStartPosition j : ZMod c.encodingPeriod) = true := by
  rw [c.oddStartWord_eq_true_iff]
  exact ⟨j, rfl⟩

end OddCycle
end Collatz
