import Collatz.Basic

namespace Collatz

/-- For an odd natural number, the unaccelerated Collatz map takes the
`3 * n + 1` branch. -/
theorem step_of_odd {n : ℕ} (hn : Odd n) : step n = 3 * n + 1 := by
  rcases hn with ⟨k, rfl⟩
  simp [step]

/-- One Collatz step halves an explicitly even number `2 * n`. -/
@[simp]
theorem step_two_mul (n : ℕ) : step (2 * n) = n := by
  simp [step]

/-- Repeated Collatz steps remove an explicitly supplied power of two. -/
theorem iterate_step_pow_two_mul (a y : ℕ) :
    (step^[a]) (2 ^ a * y) = y := by
  induction a with
  | zero => simp
  | succ a ih =>
      rw [Function.iterate_succ_apply]
      rw [pow_succ]
      have hrewrite : 2 ^ a * 2 * y = 2 * (2 ^ a * y) := by ring
      rw [hrewrite, step_two_mul]
      exact ih

/-- Arithmetic data for one exact odd-to-odd Collatz transition.

The equation records the odd `3x+1` step. The target is required to be odd, so
after the stated `a` halving steps the accelerated transition has genuinely
reached the next odd value rather than stopping early. -/
structure OddToOddStep (x y a : ℕ) : Prop where
  source_pos : 0 < x
  target_pos : 0 < y
  source_odd : Odd x
  target_odd : Odd y
  exponent_pos : 0 < a
  equation : 3 * x + 1 = 2 ^ a * y

namespace OddToOddStep

variable {x y a : ℕ}

/-- The first ordinary Collatz step of an odd-to-odd transition is exactly the
power-of-two multiple appearing in its defining arithmetic equation. -/
theorem first_step_eq (h : OddToOddStep x y a) : step x = 2 ^ a * y := by
  rw [step_of_odd h.source_odd]
  exact h.equation

/-- An exact odd-to-odd relation really is realised by the ordinary Collatz
map: one odd step followed by `a` halving steps reaches `y`. -/
theorem reaches_target (h : OddToOddStep x y a) :
    (step^[a + 1]) x = y := by
  rw [Function.iterate_succ_apply]
  rw [h.first_step_eq]
  exact iterate_step_pow_two_mul a y

end OddToOddStep

/-- A positive odd Collatz cycle with `L` odd nodes, indexed cyclically.

The index type `ZMod L` makes the closing edge part of the same local equation
as every other edge. No combinatorial Radius-4 encoding is built into this
structure. -/
structure OddCycle (L : ℕ) [NeZero L] where
  node : ZMod L → ℕ
  exponent : ZMod L → ℕ
  node_pos : ∀ i, 0 < node i
  node_odd : ∀ i, Odd (node i)
  exponent_pos : ∀ i, 0 < exponent i
  step_eq : ∀ i, 3 * node i + 1 = 2 ^ exponent i * node (i + 1)

namespace OddCycle

variable {L : ℕ} [NeZero L]

/-- The local edge at cyclic position `i`, packaged as an exact odd-to-odd
Collatz transition. -/
def edge (c : OddCycle L) (i : ZMod L) :
    OddToOddStep (c.node i) (c.node (i + 1)) (c.exponent i) where
  source_pos := c.node_pos i
  target_pos := c.node_pos (i + 1)
  source_odd := c.node_odd i
  target_odd := c.node_odd (i + 1)
  exponent_pos := c.exponent_pos i
  equation := c.step_eq i

/-- Every edge of an `OddCycle` is realised by ordinary Collatz iteration. -/
theorem edge_reaches_next (c : OddCycle L) (i : ZMod L) :
    (step^[c.exponent i + 1]) (c.node i) = c.node (i + 1) :=
  (c.edge i).reaches_target

/-- A cycle is non-trivial when at least one of its odd nodes is not `1`.
This is deliberately separate from the base cycle structure. -/
def IsNontrivial (c : OddCycle L) : Prop :=
  ∃ i : ZMod L, c.node i ≠ 1

/-- The sum of exponents on the first `k` cyclic odd-to-odd edges, starting at
index zero. At `k = L` this traverses the cycle exactly once. -/
def prefixExponent (c : OddCycle L) (k : ℕ) : ℕ :=
  ∑ j in Finset.range k, c.exponent (j : ZMod L)

@[simp]
theorem prefixExponent_zero (c : OddCycle L) : c.prefixExponent 0 = 0 := by
  simp [prefixExponent]

@[simp]
theorem prefixExponent_succ (c : OddCycle L) (k : ℕ) :
    c.prefixExponent (k + 1) = c.prefixExponent k + c.exponent (k : ZMod L) := by
  simp [prefixExponent, Finset.sum_range_succ]

/-- Total power of two removed during one traversal of the odd cycle. -/
def totalExponent (c : OddCycle L) : ℕ := c.prefixExponent L

/-- The inhomogeneous term generated by composing the first `k` odd-to-odd
relations. It is defined recursively in exactly the way composition creates it. -/
def prefixNumerator (c : OddCycle L) : ℕ → ℕ
  | 0 => 0
  | k + 1 => 3 * prefixNumerator c k + 2 ^ c.prefixExponent k

@[simp]
theorem prefixNumerator_zero (c : OddCycle L) : c.prefixNumerator 0 = 0 := by
  rfl

@[simp]
theorem prefixNumerator_succ (c : OddCycle L) (k : ℕ) :
    c.prefixNumerator (k + 1) =
      3 * c.prefixNumerator k + 2 ^ c.prefixExponent k := by
  rfl

/-- The composed inhomogeneous numerator is positive after at least one edge. -/
theorem prefixNumerator_pos (c : OddCycle L) {k : ℕ} (hk : 0 < k) :
    0 < c.prefixNumerator k := by
  cases k with
  | zero => omega
  | succ k =>
      rw [c.prefixNumerator_succ k]
      positivity

/-- Composition of the first `k` odd-to-odd equations.

This is the first substantive arithmetic bridge: the formula is derived by
induction from `OddCycle.step_eq`, rather than postulated as cycle folklore. -/
theorem composed_identity (c : OddCycle L) (k : ℕ) :
    2 ^ c.prefixExponent k * c.node (k : ZMod L) =
      3 ^ k * c.node 0 + c.prefixNumerator k := by
  induction k with
  | zero =>
      simp
  | succ k ih =>
      have hstep :
          2 ^ c.exponent (k : ZMod L) * c.node ((k + 1 : ℕ) : ZMod L) =
            3 * c.node (k : ZMod L) + 1 := by
        symm
        simpa using c.step_eq (k : ZMod L)
      calc
        2 ^ c.prefixExponent (k + 1) * c.node ((k + 1 : ℕ) : ZMod L) =
            2 ^ c.prefixExponent k *
              (2 ^ c.exponent (k : ZMod L) * c.node ((k + 1 : ℕ) : ZMod L)) := by
                rw [c.prefixExponent_succ k, pow_add]
                ring
        _ = 2 ^ c.prefixExponent k * (3 * c.node (k : ZMod L) + 1) := by
              rw [hstep]
        _ = 3 * (2 ^ c.prefixExponent k * c.node (k : ZMod L)) +
              2 ^ c.prefixExponent k := by
                ring
        _ = 3 * (3 ^ k * c.node 0 + c.prefixNumerator k) +
              2 ^ c.prefixExponent k := by
                rw [ih]
        _ = 3 ^ (k + 1) * c.node 0 + c.prefixNumerator (k + 1) := by
              rw [c.prefixNumerator_succ k, pow_succ]
              ring

/-- The composed identity after one full traversal of the odd cycle. -/
theorem full_cycle_identity (c : OddCycle L) :
    2 ^ c.totalExponent * c.node 0 =
      3 ^ L * c.node 0 + c.prefixNumerator L := by
  simpa [totalExponent] using c.composed_identity L

end OddCycle

end Collatz
