import Collatz.Basic

namespace Collatz

/-- For an odd natural number, the unaccelerated Collatz map takes the
`3 * n + 1` branch. -/
theorem step_of_odd {n : ℕ} (hn : Odd n) : step n = 3 * n + 1 := by
  rcases hn with ⟨k, rfl⟩
  simp [step]

/-- Arithmetic data for one exact odd-to-odd Collatz transition.

The equation says that after the odd Collatz step, exactly `2^a` is removed
before the next odd value `y` is reached. Oddness of `y` is part of the data;
a separate uniqueness theorem will make the word "exact" fully explicit. -/
structure OddToOddStep (x y a : ℕ) : Prop where
  source_pos : 0 < x
  target_pos : 0 < y
  source_odd : Odd x
  target_odd : Odd y
  exponent_pos : 0 < a
  equation : 3 * x + 1 = 2 ^ a * y

/-- A positive odd Collatz cycle with `L` odd nodes, indexed cyclically.

The index type `ZMod L` makes the closing edge part of the same local equation
as every other edge. No combinatorial Radius-4 encoding is built into this
structure. -/
structure OddCycle (L : ℕ) [NeZero L] where
  node : ZMod L → ℕ
  exponent : ZMod L → ℕ
  node_pos : ∀ i, 0 < node i
  node_odd : ∀ i, Odd (node i)
  exponent_pos : ∀ i, 0 < exponent i
  step_eq : ∀ i, 3 * node i + 1 = 2 ^ exponent i * node (i + 1)

namespace OddCycle

variable {L : ℕ} [NeZero L]

/-- The sum of exponents on the first `k` cyclic odd-to-odd edges, starting at
index zero. At `k = L` this traverses the cycle exactly once. -/
def prefixExponent (c : OddCycle L) (k : ℕ) : ℕ :=
  ∑ j in Finset.range k, c.exponent (j : ZMod L)

@[simp]
theorem prefixExponent_zero (c : OddCycle L) : c.prefixExponent 0 = 0 := by
  simp [prefixExponent]

@[simp]
theorem prefixExponent_succ (c : OddCycle L) (k : ℕ) :
    c.prefixExponent (k + 1) = c.prefixExponent k + c.exponent (k : ZMod L) := by
  simp [prefixExponent, Finset.sum_range_succ]

/-- Total power of two removed during one traversal of the odd cycle. -/
def totalExponent (c : OddCycle L) : ℕ := c.prefixExponent L

/-- The inhomogeneous term generated by composing the first `k` odd-to-odd
relations. It is defined recursively in exactly the way composition creates it. -/
def prefixNumerator (c : OddCycle L) : ℕ → ℕ
  | 0 => 0
  | k + 1 => 3 * prefixNumerator c k + 2 ^ c.prefixExponent k

@[simp]
theorem prefixNumerator_zero (c : OddCycle L) : c.prefixNumerator 0 = 0 := by
  rfl

@[simp]
theorem prefixNumerator_succ (c : OddCycle L) (k : ℕ) :
    c.prefixNumerator (k + 1) =
      3 * c.prefixNumerator k + 2 ^ c.prefixExponent k := by
  rfl

/-- Composition of the first `k` odd-to-odd equations.

This is the first substantive arithmetic bridge: the formula is derived by
induction from `OddCycle.step_eq`, rather than postulated as cycle folklore. -/
theorem composed_identity (c : OddCycle L) (k : ℕ) :
    2 ^ c.prefixExponent k * c.node (k : ZMod L) =
      3 ^ k * c.node 0 + c.prefixNumerator k := by
  induction k with
  | zero =>
      simp
  | succ k ih =>
      have hstep :
          2 ^ c.exponent (k : ZMod L) * c.node ((k + 1 : ℕ) : ZMod L) =
            3 * c.node (k : ZMod L) + 1 := by
        symm
        simpa using c.step_eq (k : ZMod L)
      calc
        2 ^ c.prefixExponent (k + 1) * c.node ((k + 1 : ℕ) : ZMod L) =
            2 ^ c.prefixExponent k *
              (2 ^ c.exponent (k : ZMod L) * c.node ((k + 1 : ℕ) : ZMod L)) := by
                rw [c.prefixExponent_succ k, pow_add]
                ring
        _ = 2 ^ c.prefixExponent k * (3 * c.node (k : ZMod L) + 1) := by
              rw [hstep]
        _ = 3 * (2 ^ c.prefixExponent k * c.node (k : ZMod L)) +
              2 ^ c.prefixExponent k := by
                ring
        _ = 3 * (3 ^ k * c.node 0 + c.prefixNumerator k) +
              2 ^ c.prefixExponent k := by
                rw [ih]
        _ = 3 ^ (k + 1) * c.node 0 + c.prefixNumerator (k + 1) := by
              rw [c.prefixNumerator_succ k, pow_succ]
              ring

/-- The composed identity after one full traversal of the odd cycle. -/
theorem full_cycle_identity (c : OddCycle L) :
    2 ^ c.totalExponent * c.node 0 =
      3 ^ L * c.node 0 + c.prefixNumerator L := by
  simpa [totalExponent] using c.composed_identity L

end OddCycle

end Collatz
